apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: linera-application-service-traefik-app-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: linera-application-service-traefik-app
    k8s.kuboard.cn/workload: linera-application-service-traefik-app
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares:
      kube-system-strip-linera-application-service-prefix@kubernetescrd,
      kube-system-http-redirect-https@kubernetescrd,
      kube-system-common-headers@kubernetescrd

spec:
  rules:
    - host: linera-application.hk-testnet.linerameme.fun
      http: &http_rules
        paths:
          - path: /
            backend:
              serviceName: linera-application-service
              servicePort: 9081
