apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: node-service-traefik-app-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: node-service-traefik-app
    k8s.kuboard.cn/workload: node-service-traefik-app
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure

spec:
  rules:
    - host: node-service.hk-testnet.linerameme.fun
      http: &http_rules
        paths:
          - path: /
            backend:
              serviceName: node-service
              servicePort: 50870
